const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),$=s=>document.querySelector(s);
const ui={user:$('#userScore'),cpu:$('#cpuScore'),half:$('#halfLabel'),balls:$('#balls'),strikes:$('#strikes'),outs:$('#outs'),msg:$('#message'),bat:$('#batControls'),pitch:$('#pitchControls'),field:$('#fieldControls'),wait:$('#pitchBtn'),swing:$('#swingBtn'),throw:$('#throwBtn'),restart:$('#restartBtn'),sound:$('#soundBtn'),bases:[$('#base1'),$('#base2'),$('#base3')]};
let game,last=0,animId,audioOn=true,audioCtx,keys={};
function beep(freq=440,duration=.08,type='square',volume=.035){if(!audioOn)return;audioCtx||=new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.value=volume;o.connect(g);g.connect(audioCtx.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);o.stop(audioCtx.currentTime+duration)}
function reset(){game={inning:1,half:'top',user:0,cpu:0,outs:0,balls:0,strikes:0,runners:[false,false,false],phase:'batReady',ball:null,swingAt:null,batAngle:.45,pitchType:'吏곴뎄',aim:{x:480,y:260},power:0,powerDir:1,glove:{x:480,y:410},fieldBall:null};controls('bat');message('怨듭쓣 湲곕떎?몃떎媛 ??대컢??留욎떠 ?ㅼ쐷?섏꽭??);update();cancelAnimationFrame(animId);last=performance.now();animId=requestAnimationFrame(loop)}
function controls(which){ui.bat.classList.toggle('hidden',which!=='bat');ui.pitch.classList.toggle('hidden',which!=='pitch');ui.field.classList.toggle('hidden',which!=='field');ui.restart.classList.toggle('hidden',which!=='end')}
function message(t){ui.msg.textContent=t}function update(){ui.user.textContent=game.user;ui.cpu.textContent=game.cpu;ui.half.textContent=`${game.inning}??${game.half==='top'?'珥?:'留?}`;ui.balls.textContent=game.balls;ui.strikes.textContent=game.strikes;ui.outs.textContent=game.outs;game.runners.forEach((v,i)=>ui.bases[i].classList.toggle('on',v))}

function startBatPitch(){if(game.phase!=='batReady')return;const type=['吏곴뎄','而ㅻ툕','泥댁씤吏??][Math.floor(Math.random()*3)];game.phase='batPitch';game.swingAt=null;game.batAngle=.45;game.ball={t:0,duration:type==='吏곴뎄'?920:type==='而ㅻ툕'?1250:1450,type,curve:(Math.random()-.5)*85,zone:Math.random()<.76};message(`${type}! 怨듭쓣 ?앷퉴吏 蹂댁꽭??);beep(180,.08,'sine')}
function swing(){if(game.phase==='batReady'){startBatPitch();return}if(game.phase!=='batPitch'||game.swingAt!==null)return;game.swingAt=game.ball.t/game.ball.duration;game.batAngle=-1.15;beep(210,.06)}
function finishBat(){const b=game.ball,p=game.swingAt;if(p===null)return b.zone?strike('?ㅽ듃?쇱씠??'):ball('蹂? ??怨⑤옄?듬땲??);const miss=Math.abs(p-.82);if(miss>.15)return strike(p<.82?'?덈Т 鍮좊Ⅸ ?ㅼ쐷!':'?덈Т ??? ?ㅼ쐷!');if(!b.zone&&miss>.075)return strike('諛고듃媛 ?쏅룎?섏뒿?덈떎!');beep(620,.12,'triangle',.06);const q=Math.max(0,1-miss/.15)+(Math.random()-.5)*.28;if(q>1.03&&Math.random()<.28)return hit(4,'?덈윴! ?댁옣???섍꼈?듬땲??');if(q>.73)return hit(Math.random()<.18?2:1,q>.94?'源⑤걮???덊?!':'?덊?!');out(Math.random()<.5?'?몄빞 ?뚮씪???꾩썐':'?낅낵 ?꾩썐')}
function strike(t){game.strikes++;message(t);beep(120,.13,'sawtooth');if(game.strikes>=3)out('?쇱쭊 ?꾩썐!');else next('batReady','?ㅼ쓬 怨듭쓣 湲곕떎由ъ꽭??);update()}
function ball(t){game.balls++;message(t);if(game.balls>=4)hit(1,'蹂쇰꽬! 1猷⑤줈 嫄몄뼱媛묐땲??,true);else next('batReady','?ㅼ쓬 怨듭쓣 湲곕떎由ъ꽭??);update()}
function clearCount(){game.balls=game.strikes=0}function next(phase,text,delay=850){game.phase='pause';setTimeout(()=>{if(game.phase==='pause'){game.phase=phase;message(text)}},delay)}
function advance(bases,user,walk=false){const old=[...game.runners],n=[false,false,false];let runs=0;if(bases===4)runs=old.filter(Boolean).length+1;else if(walk){n.splice(0,3,...old);if(!n[0])n[0]=true;else if(!n[1])n[1]=true;else if(!n[2])n[2]=true;else runs++}else{for(let i=2;i>=0;i--)if(old[i]){const d=i+bases;if(d>=3)runs++;else n[d]=true}n[bases-1]=true}game.runners=n;if(user)game.user+=runs;else game.cpu+=runs;return runs}
function hit(bases,t,walk=false){const runs=advance(bases,true,walk);clearCount();update();message(t+(runs?` 쨌 ${runs}???앹젏!`:''));next('batReady','?ㅼ쓬 ???',1100)}
function out(t){game.outs++;clearCount();update();message(t);beep(95,.18);if(game.outs>=3){game.phase='pause';setTimeout(changeHalf,1100)}else next(game.half==='top'?'batReady':'pitchAim','?ㅼ쓬 ???')}
function changeHalf(){game.outs=0;clearCount();game.runners=[false,false,false];if(game.half==='top'){game.half='bottom';game.phase='pitchAim';game.aim={x:480,y:260};controls('pitch');message('?섎퉬 ?쒖옉! 肄붿뒪瑜?議곗??섍퀬 ?ш뎄?섏꽭??)}else{if(game.inning>=3)return end();game.inning++;game.half='top';game.phase='batReady';controls('bat');message('怨듦꺽 ?쒖옉!')}update()}

function startThrow(){if(game.phase==='pitchAim'){game.phase='pitchPower';game.power=0;game.powerDir=1;ui.throw.textContent='?ш린???섏?湲?';message('寃뚯씠吏媛 ?????덉뿉 ?????ㅼ떆 ?꾨Ⅴ?몄슂')}else if(game.phase==='pitchPower'){const accuracy=1-Math.abs(game.power-.78);game.phase='cpuPitch';ui.throw.textContent='?ш뎄 ?쒖옉';game.ball={t:0,duration:720,accuracy,end:{...game.aim}};beep(170,.08,'sine');message(`${game.pitchType} ?ш뎄!`)}}
function resolveCpu(){const {x,y}=game.ball.end,acc=game.ball.accuracy,inZone=x>405&&x<555&&y>178&&y<338,mistake=Math.random()>(.38+acc*.47);if(!inZone&&Math.random()<.64)return cpuBall('蹂? ??먭? 李몄븯?듬땲??);if(!mistake)return cpuStrike(Math.random()<.45?'?쏆뒪???ㅽ듃?쇱씠??':'?ㅽ듃?쇱씠??');if(Math.random()<.12&&inZone&&acc<.86){const runs=advance(4,false);clearCount();update();message(`?곷? ????덈윴! ${runs}??);return next('pitchAim','?ㅼ쓬 ??먮? ?곷??섏꽭??,1200)}startField()}
function cpuStrike(t){game.strikes++;message(t);if(game.strikes>=3)out('?쇱쭊 ?꾩썐!');else next('pitchAim','肄붿뒪瑜?議곗??섏꽭??);update()}
function cpuBall(t){game.balls++;message(t);if(game.balls>=4){const runs=advance(1,false,true);clearCount();message('蹂쇰꽬'+(runs?` 쨌 ${runs}???앹젏`:''))}next('pitchAim','肄붿뒪瑜?議곗??섏꽭??);update()}
function startField(){game.phase='fielding';controls('field');game.glove={x:480,y:410};game.fieldBall={t:0,duration:2300,x:150+Math.random()*660,y:130+Math.random()*250};message('?援ш? ?댁뒿?덈떎! ?숆뎄 吏?먯쑝濡??대룞!');beep(520,.08,'triangle')}
function resolveField(){const b=game.fieldBall,d=Math.hypot(game.glove.x-b.x,game.glove.y-b.y);controls('pitch');if(d<58){beep(740,.18,'triangle');out('硫뗭쭊 罹먯튂! ?꾩썐!')}else{const bases=Math.random()<.18?2:1,runs=advance(bases,false);clearCount();update();message((bases===2?'怨듭씠 鍮좎죱?듬땲?? 2猷⑦?!':'?덊?瑜??덉슜?덉뒿?덈떎')+(runs?` 쨌 ${runs}???앹젏`:''));next('pitchAim','?ㅼ쓬 ??먮? ?곷??섏꽭??,1000)}}
function end(){game.phase='end';controls('end');update();const r=game.user===game.cpu?'臾댁듅遺!':game.user>game.cpu?'BLUE ?밸━!':'RED ?밸━!';message(`${r} 理쒖쥌 ?ㅼ퐫??${game.user} : ${game.cpu}`);beep(game.user>=game.cpu?660:110,.45,'triangle',.06)}

function drawField(){const w=canvas.width,h=canvas.height;ctx.fillStyle='#69b8dd';ctx.fillRect(0,0,w,h*.36);ctx.fillStyle='#246d4a';ctx.fillRect(0,h*.36,w,h*.64);for(let i=0;i<9;i++){ctx.fillStyle=i%2?'#287651':'#2d8058';ctx.beginPath();ctx.moveTo(w/2,h*.5);ctx.arc(w/2,h*.5,700,i*Math.PI/4.5,(i+1)*Math.PI/4.5);ctx.fill()}ctx.fillStyle='#bb8353';ctx.beginPath();ctx.moveTo(480,190);ctx.lineTo(790,455);ctx.lineTo(480,535);ctx.lineTo(170,455);ctx.closePath();ctx.fill();ctx.strokeStyle='#fff8';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(480,510);ctx.lineTo(145,220);ctx.moveTo(480,510);ctx.lineTo(815,220);ctx.stroke();[[480,485],[635,355],[480,280],[325,355]].forEach(([x,y])=>{ctx.save();ctx.translate(x,y);ctx.rotate(Math.PI/4);ctx.fillStyle='#f4ead4';ctx.fillRect(-11,-11,22,22);ctx.restore()});ctx.fillStyle='#173047';ctx.fillRect(0,150,w,50);ctx.fillStyle='#dbe7ef';for(let x=15;x<w;x+=28){ctx.globalAlpha=.55;ctx.fillRect(x,162,9,5)}ctx.globalAlpha=1}
function player(x,y,color,s=1){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.fillStyle='#efc59b';ctx.beginPath();ctx.arc(0,-31,10,0,7);ctx.fill();ctx.fillStyle=color;ctx.fillRect(-11,-21,22,29);ctx.fillStyle='#17263c';ctx.fillRect(-11,8,8,25);ctx.fillRect(3,8,8,25);ctx.restore()}
function drawBall(x,y,r){ctx.fillStyle='white';ctx.beginPath();ctx.arc(x,y,r,0,7);ctx.fill();ctx.strokeStyle='#d94a4a';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(x,y,r*.55,-1.2,1.2);ctx.stroke()}
function drawBat(){player(480,225,'#e4484e',.9);player(590,430,'#1c91df',1.35);ctx.save();ctx.translate(585,395);ctx.rotate(game.batAngle);ctx.strokeStyle='#e3b76f';ctx.lineWidth=9;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(65,-45);ctx.stroke();ctx.restore();if(game.phase==='batPitch'){const p=Math.min(1,game.ball.t/game.ball.duration),e=p*p;drawBall(480+110*e+Math.sin(p*Math.PI)*game.ball.curve,205+200*e,5+p*8)}}
function zone(){ctx.strokeStyle='#fff9';ctx.lineWidth=3;ctx.strokeRect(405,178,150,160);ctx.strokeStyle='#ffffff25';ctx.lineWidth=1;for(let i=1;i<3;i++){ctx.beginPath();ctx.moveTo(405+i*50,178);ctx.lineTo(405+i*50,338);ctx.moveTo(405,178+i*53.3);ctx.lineTo(555,178+i*53.3);ctx.stroke()}ctx.strokeStyle='#ffd447';ctx.lineWidth=3;ctx.beginPath();ctx.arc(game.aim.x,game.aim.y,15,0,7);ctx.moveTo(game.aim.x-23,game.aim.y);ctx.lineTo(game.aim.x+23,game.aim.y);ctx.moveTo(game.aim.x,game.aim.y-23);ctx.lineTo(game.aim.x,game.aim.y+23);ctx.stroke();if(game.phase==='pitchPower'){ctx.fillStyle='#07111ddd';ctx.fillRect(680,185,34,180);ctx.fillStyle='#31465c';ctx.fillRect(690,195,14,160);ctx.fillStyle='#ffd447';ctx.fillRect(690,195+(1-game.power)*160,14,game.power*160);ctx.strokeStyle='#fff';ctx.strokeRect(686,222,22,28)}if(game.phase==='cpuPitch'){const p=Math.min(1,game.ball.t/game.ball.duration);drawBall(480+(game.ball.end.x-480)*p,405+(game.ball.end.y-405)*p,12-7*p)}}
function fielding(){const b=game.fieldBall,p=Math.min(1,b.t/b.duration),arc=Math.sin(p*Math.PI)*190;drawBall(480+(b.x-480)*p,300+(b.y-300)*p-arc,8+4*(1-p));ctx.strokeStyle='#ffd447';ctx.lineWidth=4;ctx.setLineDash([10,8]);ctx.beginPath();ctx.arc(b.x,b.y,38,0,7);ctx.stroke();ctx.setLineDash([]);ctx.save();ctx.translate(game.glove.x,game.glove.y);ctx.fillStyle='#9b552d';ctx.strokeStyle='#f2b66f';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,26,.1,Math.PI*1.9);ctx.lineTo(0,9);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();ctx.fillStyle='#07111ddd';ctx.fillRect(270,25,420,12);ctx.fillStyle='#ffd447';ctx.fillRect(270,25,420*(1-p),12)}
function loop(now){const dt=Math.min(32,now-last);last=now;if(game.phase==='batPitch'){game.ball.t+=dt;if(game.batAngle<.45)game.batAngle+=dt*.006;if(game.ball.t>=game.ball.duration)finishBat()}if(game.phase==='pitchPower'){game.power+=game.powerDir*dt*.00085;if(game.power>=1){game.power=1;game.powerDir=-1}if(game.power<=0){game.power=0;game.powerDir=1}}if(game.phase==='cpuPitch'){game.ball.t+=dt;if(game.ball.t>=game.ball.duration)resolveCpu()}if(game.phase==='fielding'){const s=dt*.32;if(keys.ArrowLeft)game.glove.x-=s;if(keys.ArrowRight)game.glove.x+=s;if(keys.ArrowUp)game.glove.y-=s;if(keys.ArrowDown)game.glove.y+=s;game.glove.x=Math.max(35,Math.min(925,game.glove.x));game.glove.y=Math.max(90,Math.min(505,game.glove.y));game.fieldBall.t+=dt;if(game.fieldBall.t>=game.fieldBall.duration)resolveField()}ctx.clearRect(0,0,960,540);drawField();if(game.half==='top')drawBat();else if(game.phase==='fielding')fielding();else{player(480,430,'#238ddd',1.15);player(480,135,'#df464d',.85);zone()}animId=requestAnimationFrame(loop)}

ui.wait.onclick=startBatPitch;ui.swing.onclick=swing;ui.throw.onclick=startThrow;ui.restart.onclick=reset;ui.sound.onclick=()=>{audioOn=!audioOn;ui.sound.textContent=audioOn?'??ON':'??OFF'};
document.querySelectorAll('[data-pitch]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('[data-pitch]').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');game.pitchType=btn.dataset.pitch});
addEventListener('keydown',e=>{keys[e.key]=true;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key))e.preventDefault();if(e.key===' ')(game.half==='top'?swing:startThrow)();if(game.phase==='pitchAim'){if(e.key==='ArrowLeft')game.aim.x-=12;if(e.key==='ArrowRight')game.aim.x+=12;if(e.key==='ArrowUp')game.aim.y-=12;if(e.key==='ArrowDown')game.aim.y+=12;game.aim.x=Math.max(360,Math.min(600,game.aim.x));game.aim.y=Math.max(140,Math.min(375,game.aim.y))}});addEventListener('keyup',e=>keys[e.key]=false);
function pointer(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*960/r.width,y:(e.clientY-r.top)*540/r.height}}canvas.addEventListener('pointermove',e=>{const p=pointer(e);if(game.phase==='fielding')game.glove=p;if(game.phase==='pitchAim')game.aim=p});canvas.addEventListener('pointerdown',e=>{const p=pointer(e);if(game.phase==='fielding')game.glove=p;else if(game.phase==='pitchAim')game.aim=p});reset();

